import { AUTO, NONE, ELLIPSIS } from '../core/constants';

export default function getDefaults() {
  return {
    axisLine: true,
    axisLineFront: false,
    axisLineWidth: 1,
    axisLineDashArray: NONE,
    axisLineMargin: 0,
    axisLineColor: '#000000',
    axisLineFocusedColor: '#000000',
    axisLineDefocusedColor: '#000000',
    axisLineOpacity: 1,
    axisLineFocusedOpacity: 1,
    axisLineDefocusedOpacity: 0.5,

    backgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    backgroundFront: false,

    before: true,

    collapsed: false,

    focusRange: true,
    focusRangeFront: false,
    focusRangeApplyToTitle: false,
    focusRangeStrokeColor: '#000033',
    focusRangeFillColor: '#aaccff',
    focusRangeStrokeOpacity: 0.2,
    focusRangeFillOpacity: 0.3,
    focusRangeStrokeWidth: 1,
    focusRangeDashArray: NONE,

    focusTickMarks: false,
    focusTickMarksFront: false,
    focusTickMarkSize: 9,
    focusTickMarkMargin: 3,
    focusTickMarkWidth: 3,
    focusTickMarkColor: '#0000ff',
    focusTickMarkOpacity: 1,

    gridLines: false,
    gridLinesFront: false,
    gridLineWidth: 1,
    gridLineDashArray: '5, 5',
    gridLineColor: '#e5e5e5',
    gridLineFocusedColor: '#e5e5e5',
    gridLineDefocusedColor: '#e5e5e5',
    gridLineOpacity: 0.75,
    gridLineFocusedOpacity: 1,
    gridLineDefocusedOpacity: 0.5,

    marginInner: 0,
    marginOuter: 1,

    max: AUTO,
    maxOffset: 0,

    maxTickCount: 10,

    min: AUTO,
    minOffset: 0,

    minTickSpacing: 12,
    minTickInterval: 0,

    paddingInner: 0,
    paddingOuter: 1,

    softMin: NONE,
    softMax: NONE,

    threshold: NONE,
    thresholdFront: true,
    thresholdTitle: NONE,
    thresholdTitleBefore: false,
    thresholdTitleSnapToValue: true,
    thresholdTitleMargin: { top: 0, right: 0, bottom: 0, left: 0 },
    thresholdTitlePadding: { top: 0, right: 0, bottom: 0, left: 0 },
    thresholdTitleStrokeColor: 'none',
    thresholdTitleFocusedStrokeColor: 'none',
    thresholdTitleDefocusedStrokeColor: 'none',
    thresholdTitleFillColor: '#000000',
    thresholdTitleFocusedFillColor: '#000000',
    thresholdTitleDefocusedFillColor: '#000000',
    thresholdTitleStrokeOpacity: 1,
    thresholdTitleFocusedStrokeOpacity: 1,
    thresholdTitleDefocusedStrokeOpacity: 1,
    thresholdTitleFillOpacity: 1,
    thresholdTitleFocusedFillOpacity: 1,
    thresholdTitleDefocusedFillOpacity: 1,
    thresholdTitleBackgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    thresholdWidth: 1,
    thresholdDashArray: NONE,
    thresholdColor: '#000000',
    thresholdFocusedColor: '#000000',
    thresholdDefocusedColor: '#000000',
    thresholdOpacity: 1,
    thresholdFocusedOpacity: 1,
    thresholdDefocusedOpacity: 0.5,

    tickCount: AUTO,

    tickLabelFront: false,
    tickLabelAnchor: AUTO,
    tickLabelBackgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    tickLabelSize: AUTO,
    tickLabelMarginInner: 2,
    tickLabelMarginOuter: 1,
    tickLabelPaddingInner: 5,
    tickLabelPaddingOuter: 5,
    tickLabelStrokeWidth: 0,
    tickLabelFormat: AUTO,
    tickLabelPrefix: NONE,
    tickLabelSuffix: NONE,
    tickLabelRotation: 0,
    tickLabelStrokeColor: 'none',
    tickLabelFocusedStrokeColor: 'none',
    tickLabelDefocusedStrokeColor: 'none',
    tickLabelFillColor: '#000000',
    tickLabelFocusedFillColor: '#000000',
    tickLabelDefocusedFillColor: '#000000',
    tickLabelStrokeOpacity: 1,
    tickLabelFocusedStrokeOpacity: 1,
    tickLabelDefocusedStrokeOpacity: 0.5,
    tickLabelFillOpacity: 1,
    tickLabelFocusedFillOpacity: 1,
    tickLabelDefocusedFillOpacity: 0.5,

    tickMarks: true,
    tickMarkFront: false,
    tickMarkSize: 3,
    tickMarkMargin: 0,
    tickMarkWidth: 1,
    tickMarkColor: '#000000',
    tickMarkFocusedColor: '#000000',
    tickMarkDefocusedColor: '#000000',
    tickMarkOpacity: 1,
    tickMarkFocusedOpacity: 1,
    tickMarkDefocusedOpacity: 0.5,

    title: NONE,
    titleFront: false,
    titleBackgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    titleTruncationEnabled: true,
    titleTruncationValue: ELLIPSIS,
    titleSize: AUTO,
    titleMarginInner: 2,
    titleMarginOuter: 2,
    titlePaddingInner: 3,
    titlePaddingOuter: 3,
    titleStrokeWidth: 0,
    titleStrokeColor: 'none',
    titleFocusedStrokeColor: 'none',
    titleDefocusedStrokeColor: 'none',
    titleFillColor: '#000000',
    titleFocusedFillColor: '#000000',
    titleDefocusedFillColor: '#000000',
    titleStrokeOpacity: 1,
    titleFocusedStrokeOpacity: 1,
    titleDefocusedStrokeOpacity: 0.5,
    titleFillOpacity: 1,
    titleFocusedFillOpacity: 1,
    titleDefocusedFillOpacity: 0.5,
    visible: true
  };
}