import { AUTO, NONE, ELLIPSIS, COLOR_CURRENT } from '../core/constants';

export default function getDefaults() {
  return {
    axisLine: true,
    axisLineFront: false,
    axisLineWidth: 1,
    axisLineDashArray: NONE,
    axisLineMargin: 0,
    axisLineColor: COLOR_CURRENT,
    axisLineFocusedColor: COLOR_CURRENT,
    axisLineDefocusedColor: COLOR_CURRENT,
    axisLineOpacity: 0.65,
    axisLineFocusedOpacity: 0.65,
    axisLineDefocusedOpacity: 0.325,

    backgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    backgroundFront: false,

    before: true,

    collapsed: false,

    focusRange: true,
    focusRangeFront: false,
    focusRangeApplyToTitle: false,
    focusRangeStrokeColor: '#000033',
    focusRangeFillColor: '#aaccff',
    focusRangeStrokeOpacity: 0.2,
    focusRangeFillOpacity: 0.3,
    focusRangeStrokeWidth: 1,
    focusRangeDashArray: NONE,

    focusTickMarks: false,
    focusTickMarksFront: false,
    focusTickMarkSize: 9,
    focusTickMarkMargin: 3,
    focusTickMarkWidth: 3,
    focusTickMarkColor: '#0000ff',
    focusTickMarkOpacity: 1,

    gridLines: false,
    gridLinesFront: false,
    gridLineWidth: 1,
    gridLineDashArray: '5, 5',
    // The old '#e5e5e5' at 0.75 over white is about '#ececec'; currentColor at
    // 0.13 sits between matching that on a light page and matching a dark
    // page's grid, so one value reads as a grid line in either theme.
    gridLineColor: COLOR_CURRENT,
    gridLineFocusedColor: COLOR_CURRENT,
    gridLineDefocusedColor: COLOR_CURRENT,
    gridLineOpacity: 0.13,
    gridLineFocusedOpacity: 0.17,
    gridLineDefocusedOpacity: 0.09,

    marginInner: 0,
    marginOuter: 1,

    max: AUTO,
    maxOffset: 0,

    maxTickCount: 10,

    min: AUTO,
    minOffset: 0,

    minTickSpacing: 12,
    minTickInterval: 0,

    paddingInner: 0,
    paddingOuter: 1,

    softMin: NONE,
    softMax: NONE,

    threshold: NONE,
    thresholdFront: true,
    thresholdTitle: NONE,
    thresholdTitleBefore: false,
    thresholdTitleSnapToValue: true,
    thresholdTitleMargin: { top: 0, right: 0, bottom: 0, left: 0 },
    thresholdTitlePadding: { top: 0, right: 0, bottom: 0, left: 0 },
    thresholdTitleStrokeColor: 'none',
    thresholdTitleFocusedStrokeColor: 'none',
    thresholdTitleDefocusedStrokeColor: 'none',
    thresholdTitleFillColor: COLOR_CURRENT,
    thresholdTitleFocusedFillColor: COLOR_CURRENT,
    thresholdTitleDefocusedFillColor: COLOR_CURRENT,
    thresholdTitleStrokeOpacity: 1,
    thresholdTitleFocusedStrokeOpacity: 1,
    thresholdTitleDefocusedStrokeOpacity: 1,
    thresholdTitleFillOpacity: 1,
    thresholdTitleFocusedFillOpacity: 1,
    thresholdTitleDefocusedFillOpacity: 1,
    thresholdTitleBackgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    thresholdWidth: 1,
    thresholdDashArray: NONE,
    thresholdColor: COLOR_CURRENT,
    thresholdFocusedColor: COLOR_CURRENT,
    thresholdDefocusedColor: COLOR_CURRENT,
    thresholdOpacity: 0.65,
    thresholdFocusedOpacity: 0.65,
    thresholdDefocusedOpacity: 0.325,

    tickCount: AUTO,

    tickLabelFront: false,
    tickLabelAnchor: AUTO,
    tickLabelBackgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    tickLabelSize: AUTO,
    tickLabelMarginInner: 2,
    tickLabelMarginOuter: 1,
    tickLabelPaddingInner: 5,
    tickLabelPaddingOuter: 5,
    tickLabelStrokeWidth: 0,
    tickLabelFormat: AUTO,
    tickLabelPrefix: NONE,
    tickLabelSuffix: NONE,
    tickLabelRotation: 0,
    tickLabelStrokeColor: 'none',
    tickLabelFocusedStrokeColor: 'none',
    tickLabelDefocusedStrokeColor: 'none',
    tickLabelFillColor: COLOR_CURRENT,
    tickLabelFocusedFillColor: COLOR_CURRENT,
    tickLabelDefocusedFillColor: COLOR_CURRENT,
    tickLabelStrokeOpacity: 1,
    tickLabelFocusedStrokeOpacity: 1,
    tickLabelDefocusedStrokeOpacity: 0.5,
    tickLabelFillOpacity: 1,
    tickLabelFocusedFillOpacity: 1,
    tickLabelDefocusedFillOpacity: 0.5,

    tickMarks: true,
    tickMarkFront: false,
    tickMarkSize: 3,
    tickMarkMargin: 0,
    tickMarkWidth: 1,
    tickMarkColor: COLOR_CURRENT,
    tickMarkFocusedColor: COLOR_CURRENT,
    tickMarkDefocusedColor: COLOR_CURRENT,
    tickMarkOpacity: 0.65,
    tickMarkFocusedOpacity: 0.65,
    tickMarkDefocusedOpacity: 0.325,

    title: NONE,
    titleFront: false,
    titleBackgroundStyle: { stroke: '#000000', strokeOpacity: 0, strokeWidth: NONE, fill: NONE, fillOpacity: 0 },
    titleTruncationEnabled: true,
    titleTruncationValue: ELLIPSIS,
    titleSize: AUTO,
    titleMarginInner: 2,
    titleMarginOuter: 2,
    titlePaddingInner: 3,
    titlePaddingOuter: 3,
    titleStrokeWidth: 0,
    titleStrokeColor: 'none',
    titleFocusedStrokeColor: 'none',
    titleDefocusedStrokeColor: 'none',
    titleFillColor: COLOR_CURRENT,
    titleFocusedFillColor: COLOR_CURRENT,
    titleDefocusedFillColor: COLOR_CURRENT,
    titleStrokeOpacity: 1,
    titleFocusedStrokeOpacity: 1,
    titleDefocusedStrokeOpacity: 0.5,
    titleFillOpacity: 1,
    titleFocusedFillOpacity: 1,
    titleDefocusedFillOpacity: 0.5,
    visible: true
  };
}