import { NONE } from '../core/constants';

export default function getDefaults() {
  return {
    visible: true,
    applyFocus: true,
    snapToGroup: true,
    mouseOver: false,
    closeOnClick: true,
    filterOnSeriesClick: false,
    focusOnGroupClick: false,
    focusOnSeriesClick: false,
    focusOnGroupMouseOver: false,
    focusOnSeriesMouseOver: false,
    showControls: false,
    keepInside: false,
    minWidth: 120,
    padding: 2,
    linePadding: 3,
    alignValues: true,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderColor: 'rgba(0,0,0,0.3)',
    borderWidth: 2,
    borderRadius: 4,
    dropShadowColor: 'rgba(0,0,0,0.3)',
    dropShadowOffsetX: 0,
    dropShadowOffsetY: 5,
    dropShadowBlurRadius: 10,
    showIconColors: true,
    showIconShapes: true,
    showIconPlaceholders: true,
    iconSize: 14,
    iconSpacerSize: 4,
    iconBorderSize: 1,
    iconBorderColor: '#999999',
    iconSuppressedColor: 'rgba(255,255,255,0)',
    iconUnsuppressedColor: 'rgba(0,0,0,0.5)',
    adjustForSuppression: true,
    adjustSizeForSuppression: false,
    hideSuppressed: false,
    showMissingValues: true,
    suppressedValueText: NONE,
    suppressedValueCharacter: '-',
    missingValueText: 'N/A',
    rangeValueText: ' - '
  };
}