import { buildConfigReference } from './configReferenceModel';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'mochart-editor');
const outputPath = process.argv[2] ?? path.join(packageDir, 'src', 'mochartConfigModel.generated.ts');
const { model, integrityErrors } = buildConfigReference();

if (integrityErrors.length > 0) {
  throw new Error('Cannot generate editor model:\n' + integrityErrors.join('\n'));
}

const serialized = JSON.stringify(JSON.stringify(model));
const source = [
  '// Generated by @mochart/core scripts/generateEditorModel.ts. Do not edit.',
  "import type { MochartConfigModel } from './model.js';",
  '',
  `const model = JSON.parse(${serialized}) as MochartConfigModel;`,
  '',
  'export default model;',
  ''
].join('\n');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, source);
