export default function getDescriptions() {
  return {
    id: 'the unique identifier for the series',
    order: 'the unique order number of the series controlling its order of appearance',
    axis: 'the unique identifier of the axis that the series belongs to',
    stack: 'the unique identifier of the series stack that the series belongs to (use null for none)',
    group: 'the unique identifier of the series group that the series belongs to (use null for none)',
    property: 'the property to retrieve from the data provider for the series values',
    rangeProperty: 'the property to retrieve from the data provider for the secondary series values (use null for none)',
    markerProperty: 'the property to retrieve from the data provider for the marker size values (use null for none)',
    colorProperty: 'the property to retrieve from the data provider for the series color values (use null for none)',
    labelProperty: 'the property to retrieve from the data provider for the series label values (use null for none)',
    tooltipProperty: 'the property to retrieve from the data provider for the values shown for the series in the tooltip in place of the series values (use null for none)',
    ignore: 'whether to ignore this series and treat it as though it were not specified',
    renderer: 'the shape renderer to use when drawing the series shape (line, area, bar, none)',
    skipMissing: 'whether to skip undefined values when drawing the shape for this series',
    skipPartialRange: 'whether to treat a value as missing when either of property or rangeProperty is undefined, instead of collapsing to the defined one',
    showMissingAtBase: 'whether to use the series axis base value for missing values when drawing the shape for this series',
    curve: 'the d3 curve type and param to use when drawing the series shape',
    barWidthPercent: 'the fraction (0 - 1) of the bar layout slot width to use when drawing bars in the series',
    capSize: 'the size of the cap (in pixels) to use when drawing caps on a bar series',
    capType: 'the type (point, curve, round, use null for none) of cap to use when drawing caps on a bar series',
    capExpand: 'whether to expand the base of caps on a bar series when the size of the cap is greater than the extent of the bar',
    capOnlyStackOuter: 'whether to only show the cap on bars in the series when they are an outer series of a stack',
    valueLabel: 'the label to show before a series value in the tooltip (use null for none)',
    valueFormat: 'the d3 format string to be applied to the series value when displayed in the tooltip (use null for none, use "auto" to derive from data ("auto" will use the series axis tick label format if it is set))',
    valuePrefix: 'the text to prefix series values with when showing them in the tooltip (use null for none)',
    valueSuffix: 'the text to append series values with when showing them in the tooltip (use null for none)',
    useTitleForValueLabel: 'whether to use the title value for the valueLabel value when the valueLabel is not set',
    title: 'the title to display for the series in the legend (use null for none)',
    strokeWidth: 'the stroke width (in pixels) of the series shape',
    focusedStrokeWidth: 'the focused stroke width (in pixels) of the series shape',
    defocusedStrokeWidth: 'the defocused stroke width (in pixels) of the series shape',
    strokeOpacity: 'the stroke opacity (0 - 1) of the series shape',
    focusedStrokeOpacity: 'the focused stroke opacity (0 - 1) of the series shape',
    defocusedStrokeOpacity: 'the defocused stroke opacity (0 - 1) of the series shape',
    fillOpacity: 'the fill opacity (0 - 1) of the series shape',
    focusedFillOpacity: 'the focused fill opacity (0 - 1) of the series shape',
    defocusedFillOpacity: 'the defocused fill opacity (0 - 1) of the series shape',
    labelFormat: 'the d3 format string to be applied to the series label values (use null for none, use "auto" to derive from data)',
    labelStrokeColor: 'the stroke color to use for the series label values (use "series" to reuse the strokeColor, use "seriesIndex" to apply the colorPaletteConfig label strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig label strokeColor for the group index)',
    labelFocusedStrokeColor: 'the focused stroke color to use for the series label values (use "series" to reuse the focusedStrokeColor, use "same" to reuse the labelStrokeColor, use "seriesIndex" to apply the colorPaletteConfig labelFocused strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig labelFocused strokeColor for the group index)',
    labelDefocusedStrokeColor: 'the defocused stroke color to use for the series label values (use "series" to reuse the defocusedStrokeColor, use "same" to reuse the labelStrokeColor, use "seriesIndex" to apply the colorPaletteConfig labelDefocused strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig labelDefocused strokeColor for the group index)',
    labelFillColor: 'the fill color to use for the series label values (use "series" to reuse the fillColor, use "seriesIndex" to apply the colorPaletteConfig label fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig label fillColor for the group index)',
    labelFocusedFillColor: 'the focused fill color to use for the series label values (use "series" to reuse the focusedFillColor, use "same" to reuse the labelFillColor, use "seriesIndex" to apply the colorPaletteConfig labelFocused fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig labelFocused fillColor for the group index)',
    labelDefocusedFillColor: 'the defocused fill color to use for the series label values (use "series" to reuse the defocusedFillColor, use "same" to reuse the labelFillColor, use "seriesIndex" to apply the colorPaletteConfig labelDefocused fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig labelDefocused fillColor for the group index)',
    labelMinPositionPercent: 'the minimum position percentage (0 - 1) from the domain minimum for which series labels should be shown (use null for none)',
    labelMaxPositionPercent: 'the maximum position percentage (0 - 1) from the domain maximum for which series labels should be shown (use null for none)',
    labelMinRangePercent: 'the minimum position percentage (0 - 1) between two series values for which series labels should be shown (use null for none)',
    labelOffset: 'the series position offset (in pixels) to apply to all series label positions',
    labelPosition: 'whether to position the series labels inside or outside of the series shape',
    labelAboveBaseMinPositionPercent: 'the minimum position percentage (0 - 1) above the base value for which series labels should be shown (use null for none)',
    labelAboveBaseMaxPositionPercent: 'the maximum position percentage (0 - 1) from the domain maximum for which series labels should be shown (use null for none)',
    labelBelowBaseMinPositionPercent: 'the minimum position percentage (0 - 1) from the domain minimum for which series labels should be shown (use null for none)',
    labelBelowBaseMaxPositionPercent: 'the maximum position percentage (0 - 1) below the base value for which series labels should be shown (use null for none)',
    labelAboveBaseOffset: 'the series position offset (in pixels) to apply to all series label positions that are above the base value (use "auto" to derive from the labelOffset)',
    labelBelowBaseOffset: 'the series position offset (in pixels) to apply to all series label positions that are below the base value (use "auto" to derive from the labelOffset)',
    labelAboveBasePosition: 'whether to position the series labels inside or outside of the series shape for series shapes that are above the base value',
    labelBelowBasePosition: 'whether to position the series labels inside or outside of the series shape for series shapes that are below the base value',
    labelStrokeWidth: 'the stroke width (in pixels) for the series label text',
    labelFocusedStrokeWidth: 'the focused stroke width (in pixels) for the series label text',
    labelDefocusedStrokeWidth: 'the defocused stroke width (in pixels) for the series label text',
    labelStrokeOpacity: 'the stroke opacity (0 - 1) for the series label text',
    labelFocusedStrokeOpacity: 'the focused stroke opacity (0 - 1) for the series label text',
    labelDefocusedStrokeOpacity: 'the defocused stroke opacity (0 - 1) for the series label text',
    labelFillOpacity: 'the fill opacity (0 - 1) for the series label text',
    labelFocusedFillOpacity: 'the focused fill opacity (0 - 1) for the series label text',
    labelDefocusedFillOpacity: 'the defocused fill opacity (0 - 1) for the series label text',
    gradient: 'the unique id of the gradient config to be used when coloring the series shape (use null for none)',
    strokeColor: 'the stroke color to use for the series shape (use "seriesIndex" to apply the colorPaletteConfig series strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig series strokeColor for the group index)',
    focusedStrokeColor: 'the focused stroke color to use for the series shape (use "same" to reuse the strokeColor, use "seriesIndex" to apply the colorPaletteConfig seriesFocused strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig seriesFocused strokeColor for the group index)',
    defocusedStrokeColor: 'the defocused stroke color to use for the series shape (use "same" to reuse the strokeColor, use "seriesIndex" to apply the colorPaletteConfig seriesDefocused strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig seriesDefocused strokeColor for the group index)',
    fillColor: 'the fill color to use for the series shape (use "seriesIndex" to apply the colorPaletteConfig series fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig series fillColor for the group index)',
    focusedFillColor: 'the focused fill color to use for the series shape (use "same" to reuse the fillColor, use "seriesIndex" to apply the colorPaletteConfig seriesFocused fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig seriesFocused fillColor for the group index)',
    defocusedFillColor: 'the defocused fill color to use for the series shape (use "same" to reuse the fillColor, use "seriesIndex" to apply the colorPaletteConfig seriesDefocused fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig seriesDefocused fillColor for the group index)',
    colorMin: 'the minimum color to use when interpolating the series shape color with a colorProperty (use null for none)',
    colorMax: 'the maximum color to use when interpolating the series shape color with a colorProperty (use null for none)',
    colorBaseAboveMin: 'the minimum color to use when interpolating the series shape color with a colorProperty value that is above the colorBase (use null for none)',
    colorBaseAboveMax: 'the maximum color to use when interpolating the series shape color with a colorProperty value that is above the colorBase (use null for none)',
    colorBase: 'the base value to use for color interpolation, allowing 2 distinct sets of min & max colors for interpolation (use null for none)',
    colorBaseBelowMin: 'the minimum color to use when interpolating the series shape color with a colorProperty value that is below the colorBase (use null for none)',
    colorBaseBelowMax: 'the maximum color to use when interpolating the series shape color with a colorProperty value that is below the colorBase (use null for none)',
    colorInterpolation: 'the type of d3 color interpolation to apply when using a color property (rgb, hsl, lab, hcl) (use null for none)',
    markerStrokeColor: 'the stroke color to use for the series marker (use "series" to reuse the strokeColor, use "seriesIndex" to apply the colorPaletteConfig marker strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig marker strokeColor for the group index)',
    markerFocusedStrokeColor: 'the focused stroke color to use for the series marker (use "series" to reuse the focusedStrokeColor, use "same" to reuse the markerStrokeColor, use "seriesIndex" to apply the colorPaletteConfig markerFocused strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig markerFocused strokeColor for the group index)',
    markerDefocusedStrokeColor: 'the defocused stroke color to use for the series marker (use "series" to reuse the defocusedStrokeColor, use "same" to reuse the markerStrokeColor, use "seriesIndex" to apply the colorPaletteConfig markerDefocused strokeColor for the series index, use "groupIndex" to apply the colorPaletteConfig markerDefocused strokeColor for the group index)',
    markerFillColor: 'the fill color to use for the series marker (use "series" to reuse the fillColor, use "seriesIndex" to apply the colorPaletteConfig marker fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig marker fillColor for the group index)',
    markerFocusedFillColor: 'the focused fill color to use for the series marker (use "series" to reuse the focusedFillColor, use "same" to reuse the markerFillColor, use "seriesIndex" to apply the colorPaletteConfig markerFocused fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig markerFocused fillColor for the group index)',
    markerDefocusedFillColor: 'the defocused fill color to use for the series marker (use "series" to reuse the defocusedFillColor, use "same" to reuse the markerFillColor, use "seriesIndex" to apply the colorPaletteConfig markerDefocused fillColor for the series index, use "groupIndex" to apply the colorPaletteConfig markerDefocused fillColor for the group index)',
    markerShape: 'the shape to use when drawing the series marker (circle, cross, diamond, square, star, triangle, wye) (use null for none)',
    minMarkerSize: 'the minimum marker size (in pixels) to use when interpolating the marker size based on a marker property value',
    markerShowMissing: 'whether to show the marker when the value is missing (can be used in conjunction with showMissingAtBase)',
    markerSize: 'the maximum marker size (in pixels) to use when interpolating the marker size based on a marker property value, or the marker size when no marker property is used',
    markerStrokeWidth: 'the stroke width (in pixels) for the series marker shape',
    markerFocusedStrokeWidth: 'the focused stroke width (in pixels) for the series marker shape',
    markerDefocusedStrokeWidth: 'the defocused stroke width (in pixels) for the series marker shape',
    markerStrokeOpacity: 'the stroke opacity (0 -1) for the series marker shape',
    markerFocusedStrokeOpacity: 'the focused stroke opacity (0 -1) for the series marker shape',
    markerDefocusedStrokeOpacity: 'the defocused stroke opacity (0 -1) for the series marker shape',
    markerFillOpacity: 'the fill opacity (0 -1) for the series marker shape',
    markerFocusedFillOpacity: 'the focused fill opacity (0 -1) for the series marker shape',
    markerDefocusedFillOpacity: 'the defocused fill opacity (0 -1) for the series marker shape',
    showInLegend: 'whether to show the series in the legend',
    showInTooltip: 'whether to show the series in the tooltip',
    showColorInLegend: 'whether to show the series color as an icon next to the series title in the legend',
    showColorInTooltip: 'whether to show the series color as an icon next to the series title in the tooltip',
    suppressible: 'whether or not the series can be suppressed from being shown in the chart',
    followSeries: 'the unique identifier of another series whose legend filtering and focus this series follows (use null for none)',
    focusOnMouseOver: 'whether the series should be focused whenever the user mouses over a part of it in the chart',
    focusOnClick: 'whether the series should be focused whenever the user clicks/taps a part of it in the chart',
    focusGroupOnMouseOver: 'whether the group should be focused whenever the user mouses over a group of the series in the chart',
    focusGroupOnClick: 'whether the group should be focused whenever the user clicks/taps a group of the series in the chart',
    useAxisFocus: 'whether to show the series as focused when the series axis it belongs to is focused',
    animateBaseFromAdjacent: 'whether to animate leading/trailing series position values from their adjacent values (true) or from the base value (false)'
  };
}
export function getDetails() {
  return {
    property: 'The chart reads this property from each group of the data provider to get the series value — it is the only series property without a default, so every series must set it. Use `getDataErrors` to check a dataset against the configured properties.',
    renderer: '`bar` draws a rectangle per group value, `line` connects the values with a path, `area` fills between the value line and the series axis base, and `none` draws no shape. Different series in the same chart can use different renderers, e.g. bars with a line overlay.',
    rangeProperty: 'When set, the series shape spans from the `rangeProperty` value to the `property` value instead of starting at the axis base — producing floating bars or a banded (low/high) area.',
    axis: 'Assigns the series to the value axis in `seriesAxisConfigs` whose `id` matches. With a single configured axis this can be omitted — it defaults to that axis id.',
    stack: 'Series sharing the same stack id (an `id` from `seriesStackConfigs`) are drawn stacked on one another and animate as a single unit, so the stack stays gapless mid-transition. Defaults to the sole stack id when exactly one stack is configured; use `null` to opt a series out.',
    group: 'Series sharing the same group id (an `id` from `seriesGroupConfigs`) are laid out side by side within each group slot — grouped/clustered bars. Defaults to the sole group id when exactly one group is configured; use `null` to opt a series out.',
    curve: 'Only affects the `line` and `area` renderers. `type` selects the d3-shape curve (`linear`, `monotoneX`, `natural`, `step`, `cardinal`, `catmullRom`, …) and `param` is passed to the curve’s tension/alpha configurator for the curve types that take one.',
    skipMissing: 'When `true`, groups whose value is missing (`undefined`) are left out of the shape, so lines and areas connect directly between the neighbouring defined values; when `false` the shape breaks at the gap. For a series with a `rangeProperty`, a group counts as missing only when both properties are undefined — see `skipPartialRange`.',
    skipPartialRange: 'Only affects series with a `rangeProperty` (stacked series are unaffected). By default a group with just one of `property`/`rangeProperty` undefined keeps a zero-extent span collapsed at the defined value, so ranged areas stay connected through it. When `true` such groups count as missing instead, following the configured missing-value treatment: a break in the shape, or skipped over when `skipMissing` is set, or drawn at the base when `showMissingAtBase` is set.',
    showMissingAtBase: 'An alternative missing-value treatment: instead of leaving a gap, missing values are drawn at the series axis base value.',
    valueFormat: 'A d3-format specifier applied to the value shown in the tooltip, e.g. `".1f"` or `",.0f"`. `"auto"` derives a format from the data, preferring the series axis `tickLabelFormat` when that is set.',
    capType: 'Draws a decorative cap on the value end of each bar in the series; `capSize` controls its extent. To cap only the outside of a stacked bar, see `capOnlyStackOuter` and `seriesStackConfigs.outerCapType`.',
    barWidthPercent: 'Only affects the `bar` renderer. Narrows each bar within its layout slot (the full group slot, or the series’ sub-slot when grouped) while keeping it centered, so a narrow bar can overlay a full-width one from another series — e.g. a candlestick wick behind its body, or a bullet-chart measure over its backing range.',
    followSeries: 'When the referenced series is toggled out of (or back into) the chart via the legend, this series follows it, and it shares the referenced series’ focus state both ways: focusing the leader highlights this series too, and focus interactions on this series target the leader. For companion series hidden from the legend (`showInLegend: false`) that visually belong to a legend series — e.g. a candlestick wick following its body — so filtering or focusing treats the whole mark as one.'
  };
}
